### ISSUE TITLE
Low Fidelity Wireframes

### ISSUE THREAD

**Issue by ashleycouperus** [thePlums/web-app#10]
Create low fidelity wireframes to determine the structure of the app.

**Comment by kattysun8** [comment]
![web-app-mobile](https://user-images.githubusercontent.com/16649731/35785020-39eeebda-09eb-11e8-9169-ffc6fa0bee1f.jpg)
![web-app-palettes](https://user-images.githubusercontent.com/16649731/35785021-39fc3f6a-09eb-11e8-90b1-b057465497a6.jpg)
![wen-app-desktop](https://user-images.githubusercontent.com/16649731/35785022-3a090326-09eb-11e8-9559-7d8ed5b09448.jpg)
