### ISSUE TITLE
High Fidelity Wireframes

### ISSUE THREAD

**Issue by ashleycouperus** [thePlums/web-app#12]
Create high fidelity wireframes to represent the final look of the app.

**Comment by kattysun8** [comment]
![home all-reminder-select 1 2x](https://user-images.githubusercontent.com/16649731/35784456-c416c540-09e5-11e8-98f5-97eff9678bed.png)
![home all-reminder-select 2x](https://user-images.githubusercontent.com/16649731/35784457-c4254430-09e5-11e8-9c4a-cd2902ef9ca7.png)
![home all-reminder 2x](https://user-images.githubusercontent.com/16649731/35784458-c432bd68-09e5-11e8-82df-d13cc202a759.png)
![home all-share-send to 2x](https://user-images.githubusercontent.com/16649731/35784459-c43dbf10-09e5-11e8-8f5b-3238ffd42dca.png)
![home all-share 2x](https://user-images.githubusercontent.com/16649731/35784460-c44b6e44-09e5-11e8-9f68-b4d2b1904ec4.png)
![home all 2x](https://user-images.githubusercontent.com/16649731/35784461-c45926d8-09e5-11e8-87c2-c75094efad3b.png)
![home audio 1 2x](https://user-images.githubusercontent.com/16649731/35784462-c46b4872-09e5-11e8-87f5-e3e13985e8d2.png)
![home audio-save 2x](https://user-images.githubusercontent.com/16649731/35784463-c47b05fa-09e5-11e8-9a1f-30a9347e8eed.png)
![home audio 2x](https://user-images.githubusercontent.com/16649731/35784464-c48bc85e-09e5-11e8-94b9-e0ad0be57bc0.png)
![home folders-reminder-select 1 2x](https://user-images.githubusercontent.com/16649731/35784465-c49810b4-09e5-11e8-9951-1ba49b368f04.png)
![home folders-reminder-select 2x](https://user-images.githubusercontent.com/16649731/35784466-c4a3ff6e-09e5-11e8-8672-b3ca1b1a91b0.png)
![home folders-reminder 2x](https://user-images.githubusercontent.com/16649731/35784467-c4afc254-09e5-11e8-9970-b3a4dd4ef64f.png)
![home folders-send to 2x](https://user-images.githubusercontent.com/16649731/35784468-c4bc0f14-09e5-11e8-8413-93ba4dfdee8d.png)
![home folders-share 2x](https://user-images.githubusercontent.com/16649731/35784469-c4c8dea6-09e5-11e8-9a1e-9a2cbe2e9698.png)
![home folders 2x](https://user-images.githubusercontent.com/16649731/35784470-c4d474aa-09e5-11e8-9a0a-d6a159b96a8d.png)
![home notes 1 2x](https://user-images.githubusercontent.com/16649731/35784471-c4e0c1b0-09e5-11e8-80af-2e22ca9da593.png)
![home notes 2x](https://user-images.githubusercontent.com/16649731/35784472-c4f02e84-09e5-11e8-9956-34ba14ee92ca.png)
![home palettes 1 2x](https://user-images.githubusercontent.com/16649731/35784473-c4fcc176-09e5-11e8-9c25-d6c51021053e.png)
![home palettes 2x](https://user-images.githubusercontent.com/16649731/35784474-c5085f36-09e5-11e8-9886-7cf2dfc8d3c3.png)
![home photo 1 2x](https://user-images.githubusercontent.com/16649731/35784475-c51664d2-09e5-11e8-8313-62892809c74c.png)
![home photo 2x](https://user-images.githubusercontent.com/16649731/35784476-c5280e1c-09e5-11e8-948b-e555b6e77449.png)
![home video 1 2x](https://user-images.githubusercontent.com/16649731/35784477-c5361b4c-09e5-11e8-9101-ccb7e1282ef5.png)
![home video 2x](https://user-images.githubusercontent.com/16649731/35784478-c544ad74-09e5-11e8-880d-e0e4ac290bb6.png)
![login pop-up 2x](https://user-images.githubusercontent.com/16649731/35784479-c55023f2-09e5-11e8-8b7d-ebd9238f8810.png)
![sign up 2x](https://user-images.githubusercontent.com/16649731/35784480-c55cee98-09e5-11e8-83cf-96934135e581.png)

**Comment by ashleycouperus** [comment]
![audio 1](https://user-images.githubusercontent.com/16690285/35812232-6d376a12-0a5e-11e8-9fe4-990db1bbef27.png)
![audio 2](https://user-images.githubusercontent.com/16690285/35812233-6d5da696-0a5e-11e8-9847-098cac102532.png)
![audio](https://user-images.githubusercontent.com/16690285/35812234-6d912674-0a5e-11e8-8e32-d09628c96a88.png)
![colour palette 1](https://user-images.githubusercontent.com/16690285/35812236-6daf15c6-0a5e-11e8-8256-1189f0f07162.png)
![colour palette](https://user-images.githubusercontent.com/16690285/35812237-6dbc0b96-0a5e-11e8-806c-36509fd001bb.png)
![dashboard home - all 2](https://user-images.githubusercontent.com/16690285/35812238-6dd24190-0a5e-11e8-96a9-a6aa7a4ab414.png)
![dashboard home - all](https://user-images.githubusercontent.com/16690285/35812239-6e57d5b2-0a5e-11e8-978a-6ec489b0310e.png)
![dashboard home folders](https://user-images.githubusercontent.com/16690285/35812240-6e7b797c-0a5e-11e8-8d84-329573778ce4.png)
![dashboard home reminder 1](https://user-images.githubusercontent.com/16690285/35812241-6e8f0140-0a5e-11e8-902d-a2244b49b362.png)
![dashboard home reminder 2 2](https://user-images.githubusercontent.com/16690285/35812242-6ea2360c-0a5e-11e8-8a94-b6f391a1e570.png)
![dashboard home reminder 2 3](https://user-images.githubusercontent.com/16690285/35812243-703e923a-0a5e-11e8-980d-2c0aaaafb8c1.png)
![dashboard home share 1 1](https://user-images.githubusercontent.com/16690285/35812244-70717d76-0a5e-11e8-9e3e-a3503cdd7d4a.png)
![dashboard home share 1](https://user-images.githubusercontent.com/16690285/35812247-7106bfa8-0a5e-11e8-865b-1ec9cffa1948.png)
![login](https://user-images.githubusercontent.com/16690285/35812248-7131eb42-0a5e-11e8-811b-a4589b805195.png)
![notes 1](https://user-images.githubusercontent.com/16690285/35812249-714b4ca4-0a5e-11e8-81e4-3a62ccbdb99f.png)
![notes](https://user-images.githubusercontent.com/16690285/35812250-715ffea6-0a5e-11e8-9af9-26f9ab168e9b.png)
![photo video 1](https://user-images.githubusercontent.com/16690285/35812252-7173cab2-0a5e-11e8-9ec3-9813360d822d.png)
![photo video](https://user-images.githubusercontent.com/16690285/35812254-71864764-0a5e-11e8-8997-39b256e263f1.png)
![photo](https://user-images.githubusercontent.com/16690285/35812255-719bbe32-0a5e-11e8-8faf-1a6598a1ae80.png)
![sign up mobile](https://user-images.githubusercontent.com/16690285/35812260-722346b8-0a5e-11e8-90e3-d397f1cf9e81.png)
![sign up page](https://user-images.githubusercontent.com/16690285/35812261-723dc1f0-0a5e-11e8-9140-d4728bc393fa.png)
![video](https://user-images.githubusercontent.com/16690285/35812262-725ac3cc-0a5e-11e8-969e-fc0151d1b0fe.png)
