### ISSUE TITLE
App Idea

### ISSUE THREAD

**Issue by ashleycouperus** [thePlums/web-app#2]
- [x] Brainstorm ideas for app
- [x] Determine problem to solve.

**Comment by kattysun8** [comment]
**Idea Tracker** 
Note taker or journal to specifically help peo or keep track of those random thoughts during the day or when waking up at night. Later when it’s time to create a concept, they can look at their list of ideas. 
- Rate and categorize the ideas 
- Edit/delete
- Write to get inspiration 
- https://medium.com/@mikehlee/how-i-think-of-app-ideas-e149b869fc14
- Tips for idea development
- Ex: think of 3 craziest impossible ideas to get the creative juices flowing 
- Jot own inspiration, ideas, things we see that are cool
- Fun & Entertainment vs. Solution to a Problem
- Target Audience: Creatives

**Solving Indecisiveness**
An app that allows you to put in the options you can choose between, it shuffles them and makes the decision for you. Disappointed with the answer? Then you know to go with the other option!
- Ice cream flavour to buy
- What to do first

**Comment by kattysun8** [comment]
**The problem** we're solving is that creative individuals can't easily keep track of their daily inspiration. Photos get stored in iPhoto to DropBox, notes in Notes or Evernote, and audio clips in an app for that. When it comes to thinking of a new idea, it's rare inspiration just pops up, but it has struck the mind throughout the day. We would like to create an app that keeps daily inspiration all in one place, categorized, easy to use and add to, and has the ability to takes notes, pictures, audio recordings and doodles. When the user needs to think of an idea, they can use the app to remember things that inspired them in the past.

**Comment by kylemery** [comment]
App Ideas:

> An app that contains references and colour palettes, as well as resources, for illustration. It would be a tool for illustrators to reference for anatomy, backgrounds, styles, and other similar topics.

> An app to help someone get up off their computer and walk around. It would shut the computer off every 30 minutes and could connect to a fitbit to make sure you do 100 steps every half hour.

> An app that would track how long a designer is working on a project (records hours) and puts them into a calendar. It would also automate invoices for the person based off he hours that were done.

**Comment by ashleycouperus** [comment]
**App Ideas**

An app that helps students away at school who experience homesickness. This app would contain pictures, Skype like features to chat with family, textures and smells that relaxes them.

An app that helps students manage their finances while in school. This app will help the student stay on top of paying bills and tuition, while knowing how much money they have to spend on entertainment, food, etc. without breaking the bank.

An app to collect funds in order to help solve problems in the world. A gaming app that can be downloaded and makes money through downloads and people playing the games. The money raised from the app is donated to world problems like poverty, lack of education, etc.
