### ISSUE TITLE
Team Check-in

### ISSUE THREAD

**Issue by kattysun8** [thePlums/web-app#51]
- [ ] How did you and the sprint succeed? What was positive?
- [ ] How did you and the sprint fail? What was negative?

**Comment by ashleycouperus** [comment]
I succeeded in this sprint by completing the notes page for the website. I completed my work on time and it was ready to be reviewed in class.
The sprint didn't fail.

**Comment by kattysun8** [comment]
The sprint was successful but I coded at the very end of the sprint because I was waiting for others to code first because I felt like I needed to see the side nav on the page and code around it. Turns out I didn't, so I quickly coded my tasks and merged them with the others and it's all worked out!

**Comment by kylemery** [comment]
This sprint was very successful. I coded the top and the side nav, and helped fix other components. We are very busy trying to get the other part of the code finished.

**Comment by ashleycouperus** [comment]
@thomasjbradley
