### ISSUE TITLE
Code Rubric

### ISSUE THREAD

**Issue by ashleycouperus** [thePlums/web-app#7]
- [x] Create rubric to measure success.

**Comment by ashleycouperus** [comment]
| | 0 Not Complete | 1 OK | 2 Good | 3 Perfect!! |
| --- | --- | --- | --- | --- |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
| **Naming Conventions** | Capitals, confusing class/Id names, spaces, etc. | No capitals or spaces but class names not descriptive | Good names | Perfect naming conventions |
| **CSS Organization** | No CSS hierarchy | Confusing CSS hierarchy | Good CSS hierarchy | Perfectly organized and labeled |

**Comment by kattysun8** [comment]
**Accessibility — 1*

The website is accessible but we spent minimal effort on this category.

**Code Quality — 3*

Great indentation and good code quality overall. Good semantics.

**Naming Conventions — 3*

Perfect naming conventions, no spaces and no capitals.

**CSS Organization — 2*

CSS pages were kept specific to it's own html page. This helped for organization. In some of these CSS pages, the code is organized and has a hierarchy. In other CSS pages, it's unorganized.

**Functionality — 1.75*

Hover states are perfect. Some links are 100% functional, and some don't have an action associated with them.

**Responsive Code — 3*

Our code is fully responsive, using Media Queries and proper screen sizes. 

13.75/18

**Comment by kattysun8** [comment]
@thomasjbradley
